application: epd-example
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: "latest"